- type: department
  id: CivilianNC
  name: department-name-CivilianNC
  description: department-desc-CivilianNC
  color: "#999999"
  roles:
    - NCCitizen
    - Reaper
    - Fixer
    - EdgeRunnerSolo
    - CafeOwner

- type: department
  id: NCPD
  name: department-name-NCPD
  description: department-desc-NCPD
  color: "#1e90ff"
  roles:
    - NCPDChief
    - NCPDInspector
    - NCPDLieutenant
    - NCPDSergeant
    - NCPDOfficer

- type: department
  id: TraumaTeam
  name: department-name-TraumaTeam
  description: department-desc-TraumaTeam
  color: "#e74c3c"
  roles:
    - TraumaTeamChief
    - TraumaTeamDoctor
    - TraumaTeamParamedic
    - TraumaTeamOperative
    - TraumaTeamCoroner
    - TraumaTeamIntern

- type: department
  id: Biotechnica
  name: department-name-Biotechnica
  description: department-desc-Biotechnica
  color: "#2ecc71"
  roles:
    - BiotechnicaChief
    - BiotechnicaRigger
    - BiotechnicaBotanist
    - BiotechnicaMedTech

- type: department
  id: Militech
  name: department-name-Militech
  description: department-desc-Militech
  color: "#c0392b"
  roles:
    - MilitechChief
    - MilitechOperativeLead
    - MilitechOperative
    - MilitechRigger
    - MilitechCombatMedic
    - MilitechTech

- type: department
  id: Zhirafa
  name: department-name-Zhirafa
  description: department-desc-Zhirafa
  color: "#2ecc71"
  roles:
    - ZhirafaJanitor
