using Content.Shared._NC.RTS.Components;
using Content.Shared._NC.RTS.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._NC.RTS.UI;

[GenerateTypedNameReferences]
public sealed partial class RTSControlWindow : DefaultWindow
{
    public event Action<RTSCommandType>? OnCommandIssued;
    public event Action? OnStopIssued;

    public RTSControlWindow()
    {
        RobustXamlLoader.Load(this);

        MoveButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.Move);
        AttackMoveButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.AttackMove);
        AttackTargetButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.AttackTarget);
        PeacefulButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.SetPeacefulMode);
        NormalButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.SetNormalMode);
        AggressiveButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.SetAggressiveMode);
        HoldButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.HoldPosition);
        StopButton.OnPressed += _ => OnStopIssued?.Invoke();
    }

    public void UpdateSelectionCount(int count)
    {
        SelectionCountLabel.Text = Loc.GetString("nc-rts-selection-count", ("count", count));
    }

    public void UpdateCommandButtons(RTSCommandType? pendingCommand, RTSCommandType? activeCommand)
    {
        var highlightedCommand = pendingCommand ?? activeCommand;

        SetPressed(MoveButton, highlightedCommand == RTSCommandType.Move);
        SetPressed(AttackMoveButton, highlightedCommand == RTSCommandType.AttackMove);
        SetPressed(AttackTargetButton, highlightedCommand == RTSCommandType.AttackTarget);
        SetPressed(HoldButton, highlightedCommand == RTSCommandType.HoldPosition);
    }

    public void UpdateAggressionButtons(RTSAggressionMode? mode)
    {
        SetPressed(PeacefulButton, mode == RTSAggressionMode.Peaceful);
        SetPressed(NormalButton, mode == RTSAggressionMode.Normal);
        SetPressed(AggressiveButton, mode == RTSAggressionMode.Aggressive);
    }

    private static void SetPressed(Button button, bool pressed)
    {
        if (button.Pressed != pressed)
            button.Pressed = pressed;
    }
}
