using Content.Client.Stylesheets;
using Content.Client.UserInterface.Fragments;
using Content.Shared._NC.CitiNet.Components;
using Content.Shared._NC.CitiNet.Delivery;
using Content.Shared._NC.CitiNet.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._NC.CitiNet.UI.CorporateSupply;

[GenerateTypedNameReferences]
public sealed partial class CorporateSupplySiteUi : PanelContainer
{
    public event Action<string, string, int>? OnAddToCart;
    public event Action<string, string, int>? OnRemoveFromCart;
    public event Action? OnClearCart;
    public event Action? OnCheckoutCart;

    public CorporateSupplySiteUi()
    {
        RobustXamlLoader.Load(this);
        Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNightCity;
        ClearCartButton.OnPressed += _ => OnClearCart?.Invoke();
        CheckoutButton.OnPressed += _ => OnCheckoutCart?.Invoke();
    }

    public void UpdateState(CitiNetStoreUpdateState state)
    {
        FundsLabel.Text = Loc.GetString("citinet-store-ui-corp-funds", ("balance", state.Balance));
        DataLabel.Text = Loc.GetString("citinet-store-ui-corp-data", ("data", state.DataBalance));
        StatusLabel.Text = GetStatusText(state);

        RenderCart(state);
        RenderListings(state);
    }

    private static string GetStatusText(CitiNetStoreUpdateState state)
    {
        if (!state.UsesCorporateAccount)
            return Loc.GetString("citinet-store-ui-corp-status-no-account");

        return state.DeliveryType == DropType.CorporateZone
            ? Loc.GetString("citinet-store-ui-corp-status-zone")
            : Loc.GetString("citinet-store-ui-corp-status-dropbox");
    }

    private void RenderListings(CitiNetStoreUpdateState state)
    {
        Listings.RemoveAllChildren();

        foreach (var category in state.Categories)
        {
            Listings.AddChild(new Label
            {
                Text = Localize(category.Name).ToUpperInvariant(),
                StyleClasses = { "NightCityGlowText" },
                Margin = new Thickness(0, 8, 0, 2)
            });

            foreach (var entry in category.Entries)
            {
                AddListingRow(state, entry);
            }
        }
    }

    private void AddListingRow(CitiNetStoreUpdateState state, CitiNetStoreEntryData entry)
    {
        var isOutOfStock = entry.RemainingCount.HasValue && entry.RemainingCount.Value <= 0;

        var row = new PanelContainer
        {
            StyleClasses = { "NightCityPanelDark" },
            MinHeight = 72,
            Margin = new Thickness(0, 2)
        };

        if (isOutOfStock)
            row.Modulate = Color.FromHex("#333333");

        var hBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(8)
        };

        var icon = new EntityPrototypeView
        {
            SetSize = new Vector2(48, 48),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 8, 0)
        };
        icon.SetPrototype(entry.ProtoId);
        hBox.AddChild(icon);

        var details = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center
        };

        details.AddChild(new Label
        {
            Text = Localize(entry.Name).ToUpperInvariant(),
            StyleClasses = { "NightCityGlowText" }
        });
        details.AddChild(new Label
        {
            Text = Localize(entry.Description),
            StyleClasses = { "NightCityMutedText" },
            ClipText = true
        });

        if (entry.RemainingCount.HasValue)
        {
            details.AddChild(new Label
            {
                Text = isOutOfStock
                    ? Loc.GetString("citinet-store-ui-stock-depleted")
                    : Loc.GetString("citinet-store-ui-stock", ("count", entry.RemainingCount.Value)),
                StyleClasses = { isOutOfStock ? "NightCityStatusDanger" : "NightCityStatusGood" }
            });
        }

        hBox.AddChild(details);

        var amount = 1;
        var amountBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0)
        };
        var minusButton = new Button
        {
            Text = "-",
            MinSize = new Vector2(24, 24),
            Disabled = isOutOfStock,
            StyleClasses = { "NightCityButton" }
        };
        var amountLabel = new Label
        {
            Text = "1",
            MinWidth = 30,
            HorizontalAlignment = HAlignment.Center
        };
        var plusButton = new Button
        {
            Text = "+",
            MinSize = new Vector2(24, 24),
            Disabled = isOutOfStock,
            StyleClasses = { "NightCityButton" }
        };

        minusButton.OnPressed += _ =>
        {
            if (amount <= 1)
                return;

            amount--;
            amountLabel.Text = amount.ToString();
        };

        plusButton.OnPressed += _ =>
        {
            if (entry.RemainingCount.HasValue && amount >= entry.RemainingCount.Value)
                return;

            amount++;
            amountLabel.Text = amount.ToString();
        };

        amountBox.AddChild(minusButton);
        amountBox.AddChild(amountLabel);
        amountBox.AddChild(plusButton);

        if (!isOutOfStock)
            hBox.AddChild(amountBox);

        hBox.AddChild(new Label
        {
            Text = Loc.GetString("citinet-store-ui-price", ("price", entry.Price), ("data", entry.DataPrice)),
            VerticalAlignment = VAlignment.Center,
            MinWidth = 128,
            Margin = new Thickness(8, 0),
            StyleClasses = { "NightCityStatusWarning" }
        });

        var addButton = new Button
        {
            Text = isOutOfStock
                ? Loc.GetString("citinet-store-ui-sold-out")
                : Loc.GetString("citinet-store-ui-add-to-cart"),
            MinWidth = 112,
            VerticalAlignment = VAlignment.Center,
            Disabled = isOutOfStock || !state.UsesCorporateAccount,
            StyleClasses = { "NightCityButton" }
        };

        addButton.OnPressed += _ => OnAddToCart?.Invoke(entry.Id, entry.ProtoId, amount);
        hBox.AddChild(addButton);

        row.AddChild(hBox);
        Listings.AddChild(row);
    }

    private void RenderCart(CitiNetStoreUpdateState state)
    {
        CartEntries.RemoveAllChildren();

        CartSummaryLabel.Text = Loc.GetString(
            "citinet-store-ui-cart-summary",
            ("price", state.CartTotalPrice),
            ("data", state.CartTotalDataPrice));

        ClearCartButton.Text = Loc.GetString("citinet-store-ui-cart-clear");
        ClearCartButton.Disabled = state.CartEntries.Count == 0;
        CheckoutButton.Text = Loc.GetString("citinet-store-ui-cart-checkout");
        CheckoutButton.Disabled = !state.CanCheckout;

        if (state.CartEntries.Count == 0)
        {
            CartEntries.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-cart-empty"),
                StyleClasses = { "NightCityMutedText" }
            });
            return;
        }

        foreach (var entry in state.CartEntries)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-cart-line", ("name", Localize(entry.Name)), ("amount", entry.Amount)),
                HorizontalExpand = true,
                StyleClasses = { "NightCityMutedText" }
            });
            row.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-cart-line-price", ("price", entry.TotalPrice), ("data", entry.TotalDataPrice)),
                MinWidth = 128,
                StyleClasses = { "NightCityStatusWarning" }
            });

            var removeButton = new Button
            {
                Text = "-",
                MinWidth = 28,
                StyleClasses = { "NightCityButton" }
            };
            removeButton.OnPressed += _ => OnRemoveFromCart?.Invoke(entry.CategoryId, entry.ProtoId, 1);
            row.AddChild(removeButton);

            CartEntries.AddChild(row);
        }
    }

    private static string Localize(string text)
    {
        return Loc.TryGetString(text, out var localized) ? localized : text;
    }
}

public sealed partial class CorporateSupplySiteUiFragment : UIFragment, ICitiNetSiteFragment
{
    private CorporateSupplySiteUi? _control;

    public override Control GetUIFragmentRoot() => _control!;

    public override void Setup(BoundUserInterface userInterface, EntityUid? fragmentOwner)
    {
        _control = new CorporateSupplySiteUi();
        _control.OnAddToCart += (catId, protoId, amount) =>
            userInterface.SendMessage(new CitiNetStoreBuyRequestMessage(catId, protoId, amount));
        _control.OnRemoveFromCart += (catId, protoId, amount) =>
            userInterface.SendMessage(new CitiNetStoreRemoveFromCartMessage(catId, protoId, amount));
        _control.OnClearCart += () => userInterface.SendMessage(new CitiNetStoreClearCartMessage());
        _control.OnCheckoutCart += () => userInterface.SendMessage(new CitiNetStoreCheckoutCartMessage());

        userInterface.SendMessage(new CitiNetStoreRequestDataMessage());
    }

    public override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is CitiNetStoreUpdateState storeState)
            _control?.UpdateState(storeState);
    }

    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
    }
}
