using Content.Shared._NC.CitiNet;
using Content.Shared._NC.CitiNet.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.CitiNet.UI;

[GenerateTypedNameReferences]
public sealed partial class NetHomeSiteUI : BoxContainer
{
    private readonly IPrototypeManager _protoManager;
    public event Action<string>? OnNavigate;

    public NetHomeSiteUI()
    {
        try 
        {
            RobustXamlLoader.Load(this);
            _protoManager = IoCManager.Resolve<IPrototypeManager>();
        }
        catch (Exception e)
        {
            Logger.ErrorS("citinet.browser", $"NetHomeSiteUI XAML LOAD CRASH: {e}");
            throw;
        }
    }

    public void UpdateState(NetBrowserUiState state)
    {
        if (SiteList == null)
            return;

        SiteList.RemoveAllChildren();
        SiteList.AddChild(new Label
        {
            Text = Loc.GetString("citinet-home-services"),
            StyleClasses = { "NightCityStatusDanger" },
            Margin = new Thickness(0, 0, 0, 10)
        });

        foreach (var siteId in state.AvailableSiteIds)
        {
            if (!_protoManager.TryIndex<NetSitePrototype>(siteId, out var site))
                continue;

            // Skip home itself.
            if (site.URL == "nightcity.gov")
                continue;

            var btn = new Button { 
                Text = LocalizeSiteName(site.Name).ToUpperInvariant(),
                MinWidth = 200,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                ClipText = true,
                Margin = new Thickness(0, 0, 0, 3),
                StyleClasses = { "NightCityButton" }
            };
            
            var url = site.URL;
            btn.OnPressed += _ => OnNavigate?.Invoke(url);
            SiteList.AddChild(btn);
        }
    }

    private static string LocalizeSiteName(string name)
    {
        return Loc.TryGetString(name, out var localized) ? localized : name;
    }
}
