using System.Numerics;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;


namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control, ILocalizedControl
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    // public Button CharacterSetupButton => CharacterSetup;

    private readonly Texture BackgroundTexture; //WWDP EDIT

    private EntityUid? _previewDummy;
    private HumanoidCharacterProfile? _profile;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        BackgroundTexture = _resourceCache.GetResource<TextureResource>("/Textures/_White/NovaUI/Paper/photo_scaled.png").Texture; //WWDP EDIT
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        // Keep profile data instead of localized text so language changes can rebuild both labels.
        _profile = profile;
        Relocalize();
    }

    public void Relocalize()
    {
        if (_profile == null)
        {
            Summary.Text = string.Empty;
            Balance.Text = string.Empty;
            Balance.Visible = false;
            return;
        }

        Summary.Text = _profile.Summary;
        Balance.Text = Loc.GetString("nc-character-bank-balance", ("balance", _profile.BankBalance));
        Balance.Visible = true;
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        ViewBox.DisposeAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(4f, 4f),
            MaxSize = new Vector2(112, 112),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        //WWDP EDIT START
        var panelContainer = new PanelContainer()
        {
            PanelOverride = new StyleBoxTexture()
            {
                Texture = BackgroundTexture
            },
            SetSize = new Vector2(192,192),
        };

        panelContainer.AddChild(spriteView);

        ViewBox.AddChild(panelContainer);
        //WWDP EDIT END
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = null;
    }
}
