using Content.Client.Stylesheets;
using Content.Client.UserInterface.Fragments;
using Content.Shared._NC.CitiNet.Components;
using Content.Shared._NC.CitiNet.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._NC.CitiNet.UI.FixerMarket;

[GenerateTypedNameReferences]
public sealed partial class FixerMarketSiteUi : PanelContainer
{
    public event Action<string, string, int>? OnAddToCart;
    public event Action<string, string, int>? OnRemoveFromCart;
    public event Action? OnClearCart;
    public event Action? OnCheckoutCart;

    private CitiNetStoreUpdateState? _lastState;
    private string _selectedCategory = string.Empty;
    private bool _syncingCategorySelect;

    public FixerMarketSiteUi()
    {
        RobustXamlLoader.Load(this);
        Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNightCity;
        CategoryLabel.Text = Loc.GetString("citinet-store-ui-category");
        CategorySelect.PrefixMargin = false;
        CategorySelect.OnItemSelected += OnCategorySelected;
        ClearCartButton.OnPressed += _ => OnClearCart?.Invoke();
        CheckoutButton.OnPressed += _ => OnCheckoutCart?.Invoke();
    }

    public void UpdateState(CitiNetStoreUpdateState state)
    {
        _lastState = state;
        BalanceLabel.Text = Loc.GetString("citinet-store-ui-balance", ("balance", state.Balance));
        SyncCategorySelect(state);
        RenderCart(state);
        RenderListings(state);
    }

    private void OnCategorySelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_syncingCategorySelect || _lastState == null)
            return;

        if (args.Id < 0 || args.Id >= _lastState.Categories.Count)
            return;

        CategorySelect.SelectId(args.Id);
        _selectedCategory = _lastState.Categories[args.Id].Name;
        RenderListings(_lastState);
    }

    private void SyncCategorySelect(CitiNetStoreUpdateState state)
    {
        if (state.Categories.Count == 0)
        {
            _selectedCategory = string.Empty;
            CategorySelect.Clear();
            CategorySelect.AddItem(Loc.GetString("citinet-store-ui-no-categories"), 0);
            CategorySelect.SelectId(0);
            CategorySelect.Disabled = true;
            return;
        }

        var selectedIndex = state.Categories.FindIndex(category => category.Name == _selectedCategory);
        if (selectedIndex < 0)
        {
            selectedIndex = 0;
            _selectedCategory = state.Categories[0].Name;
        }

        _syncingCategorySelect = true;
        CategorySelect.Clear();
        for (var i = 0; i < state.Categories.Count; i++)
            CategorySelect.AddItem(Localize(state.Categories[i].Name), i);

        CategorySelect.SelectId(selectedIndex);
        CategorySelect.Disabled = false;
        _syncingCategorySelect = false;
    }

    private void RenderListings(CitiNetStoreUpdateState state)
    {
        Listings.RemoveAllChildren();

        var category = state.Categories.Find(category => category.Name == _selectedCategory);
        if (category == null)
        {
            Listings.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-no-categories"),
                StyleClasses = { "NightCityMutedText" }
            });
            return;
        }

        Listings.AddChild(new Label
        {
            Text = Localize(category.Name).ToUpperInvariant(),
            StyleClasses = { "NightCityGlowText" },
            Margin = new Thickness(0, 4, 0, 2)
        });

        foreach (var entry in category.Entries)
        {
            var isOutOfStock = entry.RemainingCount.HasValue && entry.RemainingCount.Value <= 0;
            Listings.AddChild(CreateListingRow(entry, isOutOfStock));
        }
    }

    private Control CreateListingRow(CitiNetStoreEntryData entry, bool isOutOfStock)
    {
        var row = new PanelContainer { StyleClasses = { "NightCityPanelDark" }, MinHeight = 60, Margin = new Thickness(2) };
        if (isOutOfStock)
            row.Modulate = Color.FromHex("#333333");

        var hBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(8) };

        var icon = new EntityPrototypeView { SetSize = new Vector2(48, 48), VerticalAlignment = VAlignment.Center, Margin = new Thickness(0, 0, 8, 0) };
        icon.SetPrototype(entry.ProtoId);
        hBox.AddChild(icon);

        var details = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true, VerticalAlignment = VAlignment.Center };
        details.AddChild(new Label { Text = Localize(entry.Name).ToUpperInvariant(), StyleClasses = { "NightCityGlowText" } });
        details.AddChild(new Label { Text = Localize(entry.Description), StyleClasses = { "NightCityMutedText" }, ClipText = true });

        if (entry.RemainingCount.HasValue)
        {
            details.AddChild(new Label
            {
                Text = isOutOfStock
                    ? Loc.GetString("citinet-store-ui-stock-depleted")
                    : Loc.GetString("citinet-store-ui-stock", ("count", entry.RemainingCount.Value)),
                StyleClasses = { isOutOfStock ? "NightCityStatusDanger" : "NightCityStatusGood" }
            });
        }

        hBox.AddChild(details);

        var amount = 1;
        var amountBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, VerticalAlignment = VAlignment.Center, Margin = new Thickness(8, 0) };
        var minusBtn = new Button { Text = "-", MinSize = new Vector2(24, 24), Disabled = isOutOfStock, StyleClasses = { "NightCityButton" } };
        var amountLabel = new Label { Text = "1", MinWidth = 30, HorizontalAlignment = HAlignment.Center };
        var plusBtn = new Button { Text = "+", MinSize = new Vector2(24, 24), Disabled = isOutOfStock, StyleClasses = { "NightCityButton" } };

        minusBtn.OnPressed += _ =>
        {
            if (amount <= 1)
                return;

            amount--;
            amountLabel.Text = amount.ToString();
        };

        plusBtn.OnPressed += _ =>
        {
            if (entry.RemainingCount.HasValue && amount >= entry.RemainingCount.Value)
                return;

            amount++;
            amountLabel.Text = amount.ToString();
        };

        amountBox.AddChild(minusBtn);
        amountBox.AddChild(amountLabel);
        amountBox.AddChild(plusBtn);

        if (!isOutOfStock)
            hBox.AddChild(amountBox);

        hBox.AddChild(new Label
        {
            Text = Loc.GetString("citinet-store-ui-price-money", ("price", entry.Price)),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
            MinWidth = 84,
            StyleClasses = { "NightCityStatusWarning" }
        });

        var addButton = new Button
        {
            Text = isOutOfStock ? Loc.GetString("citinet-store-ui-sold-out") : Loc.GetString("citinet-store-ui-add-to-cart"),
            MinWidth = 100,
            VerticalAlignment = VAlignment.Center,
            Disabled = isOutOfStock,
            StyleClasses = { "NightCityButton" }
        };

        addButton.OnPressed += _ => OnAddToCart?.Invoke(entry.Id, entry.ProtoId, amount);
        hBox.AddChild(addButton);

        row.AddChild(hBox);
        return row;
    }

    private void RenderCart(CitiNetStoreUpdateState state)
    {
        CartEntries.RemoveAllChildren();

        CartSummaryLabel.Text = Loc.GetString(
            "citinet-store-ui-cart-summary-money",
            ("price", state.CartTotalPrice));

        ClearCartButton.Text = Loc.GetString("citinet-store-ui-cart-clear");
        ClearCartButton.Disabled = state.CartEntries.Count == 0;
        CheckoutButton.Text = Loc.GetString("citinet-store-ui-cart-checkout");
        CheckoutButton.Disabled = !state.CanCheckout;

        if (state.CartEntries.Count == 0)
        {
            CartEntries.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-cart-empty"),
                StyleClasses = { "NightCityMutedText" }
            });
            return;
        }

        foreach (var entry in state.CartEntries)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-cart-line", ("name", Localize(entry.Name)), ("amount", entry.Amount)),
                HorizontalExpand = true,
                StyleClasses = { "NightCityMutedText" }
            });
            row.AddChild(new Label
            {
                Text = Loc.GetString("citinet-store-ui-cart-line-price-money", ("price", entry.TotalPrice)),
                MinWidth = 120,
                StyleClasses = { "NightCityStatusWarning" }
            });

            var removeButton = new Button { Text = "-", MinWidth = 28, StyleClasses = { "NightCityButton" } };
            removeButton.OnPressed += _ => OnRemoveFromCart?.Invoke(entry.CategoryId, entry.ProtoId, 1);
            row.AddChild(removeButton);

            CartEntries.AddChild(row);
        }
    }

    private static string Localize(string text)
    {
        return Loc.TryGetString(text, out var localized) ? localized : text;
    }
}

public sealed partial class FixerMarketUIFragment : UIFragment, ICitiNetSiteFragment
{
    private FixerMarketSiteUi? _control;

    public override Control GetUIFragmentRoot() => _control!;

    public override void Setup(BoundUserInterface userInterface, EntityUid? fragmentOwner)
    {
        _control = new FixerMarketSiteUi();
        _control.OnAddToCart += (catId, protoId, amount) => userInterface.SendMessage(new CitiNetStoreBuyRequestMessage(catId, protoId, amount));
        _control.OnRemoveFromCart += (catId, protoId, amount) => userInterface.SendMessage(new CitiNetStoreRemoveFromCartMessage(catId, protoId, amount));
        _control.OnClearCart += () => userInterface.SendMessage(new CitiNetStoreClearCartMessage());
        _control.OnCheckoutCart += () => userInterface.SendMessage(new CitiNetStoreCheckoutCartMessage());

        userInterface.SendMessage(new CitiNetStoreRequestDataMessage());
    }

    public override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is CitiNetStoreUpdateState storeState)
            _control?.UpdateState(storeState);
    }

    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
    }
}
