using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Administration.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._NC.Administration.Whitelist;

/// <summary>
/// Displays and edits a paginated view of the global server whitelist.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WhitelistPanelWindow : FancyWindow
{
    public event Action<string>? OnSearch;
    public event Action<string>? OnAdd;
    public event Action<NetUserId>? OnRemove;
    public event Action<int>? OnSetPage;
    public event Action? OnRefresh;

    private int _page;

    public WhitelistPanelWindow()
    {
        RobustXamlLoader.Load(this);

        SearchButton.OnPressed += _ => SubmitSearch();
        SearchInput.OnTextEntered += _ => SubmitSearch();
        AddButton.OnPressed += _ => SubmitAdd();
        AddInput.OnTextEntered += _ => SubmitAdd();
        PreviousButton.OnPressed += _ => OnSetPage?.Invoke(_page - 1);
        NextButton.OnPressed += _ => OnSetPage?.Invoke(_page + 1);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void HandleState(WhitelistPanelEuiState state)
    {
        _page = state.Page;
        if (SearchInput.Text != state.Search)
            SearchInput.Text = state.Search;

        Entries.RemoveAllChildren();
        if (state.Entries.Count == 0)
        {
            Entries.AddChild(new Label
            {
                Text = Loc.GetString("nc-whitelist-panel-empty"),
                Margin = new Thickness(8),
            });
        }
        else
        {
            foreach (var entry in state.Entries)
                Entries.AddChild(CreateEntry(entry));
        }

        var pageCount = Math.Max(1, (state.Total + state.PageSize - 1) / state.PageSize);
        TotalLabel.Text = Loc.GetString("nc-whitelist-panel-total", ("count", state.Total));
        PageLabel.Text = Loc.GetString(
            "nc-whitelist-panel-page",
            ("page", state.Page + 1),
            ("pages", pageCount));
        PreviousButton.Disabled = state.Page <= 0;
        NextButton.Disabled = state.Page + 1 >= pageCount;
        StatusLabel.Text = GetStatusText(state.Status, state.StatusTarget);
    }

    private Control CreateEntry(WhitelistPanelEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 3),
        };

        row.AddChild(new Label
        {
            Text = $"{entry.Username}    {entry.UserId}",
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });

        var remove = new Button
        {
            Text = Loc.GetString("nc-whitelist-panel-remove"),
        };
        remove.OnPressed += _ => OnRemove?.Invoke(entry.UserId);
        row.AddChild(remove);

        return row;
    }

    private void SubmitSearch()
    {
        OnSearch?.Invoke(SearchInput.Text);
    }

    private void SubmitAdd()
    {
        var player = AddInput.Text.Trim();
        if (player.Length == 0)
            return;

        OnAdd?.Invoke(player);
        AddInput.Text = string.Empty;
    }

    private static string GetStatusText(WhitelistPanelStatus status, string target)
    {
        var locId = status switch
        {
            WhitelistPanelStatus.Added => "nc-whitelist-panel-status-added",
            WhitelistPanelStatus.Removed => "nc-whitelist-panel-status-removed",
            WhitelistPanelStatus.AlreadyWhitelisted => "nc-whitelist-panel-status-existing",
            WhitelistPanelStatus.NotWhitelisted => "nc-whitelist-panel-status-missing",
            WhitelistPanelStatus.PlayerNotFound => "nc-whitelist-panel-status-not-found",
            WhitelistPanelStatus.InvalidRequest => "nc-whitelist-panel-status-error",
            _ => null,
        };

        return locId is null ? string.Empty : Loc.GetString(locId, ("player", target));
    }
}
