using System.Linq;
using Content.Shared._NC.Netrunning.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberdeckTerminalWindow : DefaultWindow
{
    public event Action<string, string, NetEntity?>? OnCompileRequested;
    public event Action<NetEntity>? OnRunRequested;
    public event Action<NetEntity>? OnEjectRequested;
    public event Action? OnHotSimRequested;
    public event Action<string, NetEntity>? OnConstructRequested;

    private NetEntity? _selectedShard;
    private Dictionary<NetEntity, (string Name, string Source)> _shardData = new();
    private List<NetModuleInfo> _availableModules = new();
    private List<NetAnchorInfo> _availableAnchors = new();
    private string _logBuffer = "";

    public CyberdeckTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        HotSimButton.OnPressed += _ => OnHotSimRequested?.Invoke();
        ConstructButton.OnPressed += _ =>
        {
            var selectedModule = ModuleList.GetSelected().FirstOrDefault();
            var selectedPort = PortList.GetSelected().FirstOrDefault();

            if (selectedModule != null && selectedPort != null)
            {
                OnConstructRequested?.Invoke((string)selectedModule.Metadata!, (NetEntity)selectedPort.Metadata!);
            }
        };

        ModuleList.OnItemSelected += args =>
        {
            var id = (string)args.ItemList[args.ItemIndex].Metadata!;
            var module = _availableModules.FirstOrDefault(m => m.Id == id);
            if (module != null)
            {
                ModuleDesc.SetMessage($"Name: {module.Name}\nCost: {module.RamCost} RAM\nPrice: {module.Price} Eddies\n\n{module.Description}");
            }
        };

        CompileNewButton.OnPressed += _ => OnCompileRequested?.Invoke(Rope.Collapse(CodeInput.TextRope), NameInput.Text, null);
        SaveButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnCompileRequested?.Invoke(Rope.Collapse(CodeInput.TextRope), NameInput.Text, _selectedShard);
        };

        RunButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnRunRequested?.Invoke(_selectedShard.Value);
        };

        EditButton.OnPressed += _ =>
        {
            if (_selectedShard != null && _shardData.TryGetValue(_selectedShard.Value, out var data))
            {
                CodeInput.TextRope = new Rope.Leaf(data.Source);
                NameInput.Text = data.Name;
            }
        };

        EjectButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnEjectRequested?.Invoke(_selectedShard.Value);
        };

        ShardList.OnItemSelected += args =>
        {
            _selectedShard = (NetEntity) ShardList[args.ItemIndex].Metadata!;
        };
    }

    public void UpdateState(CyberdeckUiState state)
    {
        RamLabel.Text = $"RAM: {state.CurrentRam}/{state.MaxRam}";
        
        if (!state.HasAR)
        {
            TargetLabel.Text = "Connection: OFFLINE (AR Overlay Required)";
            TargetLabel.FontColorOverride = Color.Red;
            RunButton.Disabled = true;
            RunButton.ToolTip = "Requires AR Glasses to execute remote scripts.";
        }
        else
        {
            TargetLabel.Text = state.ActiveTarget != null ? $"Link: Linked" : "Link: Ready";
            TargetLabel.FontColorOverride = state.ActiveTarget != null ? Color.Green : Color.LightGray;
            RunButton.Disabled = false;
            RunButton.ToolTip = null;
        }

        ShardList.Clear();
        _shardData.Clear();
        foreach (var (shard, name, source) in state.Shards)
        {
            ShardList.AddItem(name, metadata: shard);
            _shardData[shard] = (name, source);
        }

        ModuleList.Clear();
        _availableModules = state.AvailableModules;
        foreach (var module in _availableModules)
        {
            ModuleList.AddItem(module.Name, metadata: module.Id);
        }

        PortList.Clear();
        _availableAnchors = state.AvailableAnchors;
        foreach (var port in _availableAnchors)
        {
            var text = port.Connected ? $"[Occupied] Port {port.Dir}" : $"Port {port.Dir}";
            var item = PortList.AddItem(text, metadata: port.Uid);
            item.Disabled = port.Connected;
        }
    }

    public void AddLog(string text)
    {
        _logBuffer += text + "\n";
        LogOutput.SetMessage(_logBuffer);
    }
}
