using System.Linq;
using Content.Shared._NC.Netrunning.Components;
using Content.Shared._NC.Netrunning.Meta;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberdeckTerminalWindow : DefaultWindow
{
    public event Action<string, string, MetaProgramKind, NetEntity?>? OnCompileRequested;
    public event Action<NetEntity>? OnRunRequested;
    public event Action<NetEntity>? OnEjectRequested;
    public event Action? OnHotSimRequested;

    private NetEntity? _selectedShard;
    private Dictionary<NetEntity, (string Name, string Source, MetaProgramKind Kind, int RamCost, MetaProgramRuntimeState RuntimeState)> _shardData = new();
    private string _logBuffer = "";
    private bool _hasAr;

    public CyberdeckTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("netrunning-cyberdeck-title");
        HeaderTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-header");
        HeaderSubtitleLabel.Text = Loc.GetString("netrunning-cyberdeck-subtitle");
        HotSimButton.Text = Loc.GetString("netrunning-cyberdeck-immersion");
        RamAvailableTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-ram-available");
        RamReservedTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-ram-reserved");
        RamRecoveringTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-ram-recovering");
        RamSpeedTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-ram-speed");
        GasBudgetTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-gas-budget");
        GasProcessTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-gas-process");
        HeatTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-heat");
        Tabs.SetTabTitle(0, Loc.GetString("netrunning-cyberdeck-tab-editor"));
        Tabs.SetTabTitle(1, Loc.GetString("netrunning-cyberdeck-tab-shards"));
        Tabs.SetTabTitle(2, Loc.GetString("netrunning-cyberdeck-tab-logs"));
        ProgramNameLabel.Text = Loc.GetString("netrunning-cyberdeck-program-name");
        NameInput.PlaceHolder = Loc.GetString("netrunning-cyberdeck-program-name-placeholder");
        DefensiveModeCheck.Text = Loc.GetString("netrunning-cyberdeck-defensive-mode");
        SourceLabel.Text = Loc.GetString("netrunning-cyberdeck-source");
        CompileNewButton.Text = Loc.GetString("netrunning-cyberdeck-compile-new");
        SaveButton.Text = Loc.GetString("netrunning-cyberdeck-save");
        InstalledShardsLabel.Text = Loc.GetString("netrunning-cyberdeck-installed-shards");
        RunButton.Text = Loc.GetString("netrunning-cyberdeck-run");
        EditButton.Text = Loc.GetString("netrunning-cyberdeck-edit");
        EjectButton.Text = Loc.GetString("netrunning-cyberdeck-eject");
        LogsTitleLabel.Text = Loc.GetString("netrunning-cyberdeck-logs");

        HotSimButton.OnPressed += _ => OnHotSimRequested?.Invoke();

        CompileNewButton.OnPressed += _ => OnCompileRequested?.Invoke(
            Rope.Collapse(CodeInput.TextRope),
            NameInput.Text,
            DefensiveModeCheck.Pressed ? MetaProgramKind.DaemonDefensive : MetaProgramKind.Standard,
            null);
        SaveButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
            {
                OnCompileRequested?.Invoke(
                    Rope.Collapse(CodeInput.TextRope),
                    NameInput.Text,
                    DefensiveModeCheck.Pressed ? MetaProgramKind.DaemonDefensive : MetaProgramKind.Standard,
                    _selectedShard);
            }
        };

        RunButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnRunRequested?.Invoke(_selectedShard.Value);
        };

        EditButton.OnPressed += _ =>
        {
            if (_selectedShard != null && _shardData.TryGetValue(_selectedShard.Value, out var data))
            {
                CodeInput.TextRope = new Rope.Leaf(data.Source);
                NameInput.Text = data.Name;
                DefensiveModeCheck.Pressed = data.Kind == MetaProgramKind.DaemonDefensive;
            }
        };

        EjectButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnEjectRequested?.Invoke(_selectedShard.Value);
        };

        ShardList.OnItemSelected += args =>
        {
            _selectedShard = (NetEntity) ShardList[args.ItemIndex].Metadata!;
            RefreshShardActionState();
        };
    }

    public void UpdateState(CyberdeckUiState state)
    {
        _hasAr = state.HasAR;
        var recoveringRam = Math.Max(0, state.MaxRam - state.CurrentRam - state.ReservedRam);
        RamAvailableLabel.Text = Loc.GetString("netrunning-cyberdeck-ram-value",
            ("current", state.CurrentRam), ("max", state.MaxRam));
        RamReservedLabel.Text = state.ReservedRam.ToString();
        RamRecoveringLabel.Text = recoveringRam.ToString();
        RamSpeedLabel.Text = Loc.GetString("netrunning-cyberdeck-ram-speed-value", ("speed", state.RecoverySpeed));
        GasBudgetLabel.Text = state.GasLimit.ToString();
        GasProcessLabel.Text = GetGasProcessText(state);
        GasProcessLabel.FontColorOverride = state.LastExecutionFailure switch
        {
            MetaExecutionFailure.GasExhausted or MetaExecutionFailure.RuntimeError or
                MetaExecutionFailure.Overheated => Color.Red,
            _ when state.LastExecutionRunning => Color.Yellow,
            _ => Color.LightGreen
        };
        HeatLabel.Text = Loc.GetString("netrunning-cyberdeck-heat-value",
            ("current", MathF.Round(state.CurrentHeat, 1)),
            ("max", MathF.Round(state.MaxHeat, 1)),
            ("cooling", state.CoolingPerSecond));
        var heatRatio = state.MaxHeat > 0f ? state.CurrentHeat / state.MaxHeat : 0f;
        HeatLabel.FontColorOverride = heatRatio switch
        {
            >= 0.9f => Color.Red,
            >= 0.65f => Color.Orange,
            _ => Color.LightGreen
        };
        TraceLabel.Text = Loc.GetString("netrunning-cyberdeck-trace", ("trace", state.CurrentTrace));
        StorageLabel.Text = Loc.GetString("netrunning-cyberdeck-storage",
            ("used", state.StorageUsed), ("capacity", state.StorageCapacity));
        ServerLoadLabel.Text = state.ActiveServer == null
            ? Loc.GetString("netrunning-cyberdeck-server-offline")
            : Loc.GetString("netrunning-cyberdeck-server-load", ("used", state.ServerUsedLoad), ("max", state.ServerMaxLoad));
        
        if (!state.HasAR)
        {
            TargetLabel.Text = Loc.GetString("netrunning-cyberdeck-connection-offline");
            TargetLabel.FontColorOverride = Color.Red;
        }
        else
        {
            TargetLabel.Text = state.ActiveTarget != null
                ? Loc.GetString("netrunning-cyberdeck-link-linked")
                : Loc.GetString("netrunning-cyberdeck-link-ready");
            TargetLabel.FontColorOverride = state.ActiveTarget != null ? Color.Green : Color.LightGray;
        }

        _shardData.Clear();
        foreach (var (shard, name, source, kind, ramCost, runtimeState) in state.Shards)
        {
            _shardData[shard] = (name, source, kind, ramCost, runtimeState);
        }

        ShardList.Clear();
        foreach (var (shard, data) in _shardData)
        {
            ShardList.AddItem(GetShardDisplayName(data), metadata: shard);
        }

        if (_selectedShard == null)
            DefensiveModeCheck.Pressed = false;

        RefreshShardActionState();
    }

    private static string GetGasProcessText(CyberdeckUiState state)
    {
        if (state.LastExecutionRunning)
        {
            return Loc.GetString("netrunning-cyberdeck-gas-running",
                ("spent", state.LastGasSpent),
                ("limit", state.GasLimit));
        }

        return state.LastExecutionFailure switch
        {
            MetaExecutionFailure.GasExhausted => Loc.GetString("netrunning-cyberdeck-gas-exhausted",
                ("spent", state.LastGasSpent),
                ("limit", state.GasLimit)),
            MetaExecutionFailure.RuntimeError => Loc.GetString("netrunning-cyberdeck-gas-runtime-error",
                ("spent", state.LastGasSpent),
                ("limit", state.GasLimit)),
            MetaExecutionFailure.Overheated => Loc.GetString("netrunning-cyberdeck-gas-overheated",
                ("spent", state.LastGasSpent),
                ("limit", state.GasLimit)),
            _ when state.LastGasSpent > 0 => Loc.GetString("netrunning-cyberdeck-gas-complete",
                ("spent", state.LastGasSpent),
                ("limit", state.GasLimit)),
            _ => Loc.GetString("netrunning-cyberdeck-gas-idle")
        };
    }

    public void AddLog(string text)
    {
        _logBuffer += text + "\n";
        LogOutput.SetMessage(_logBuffer);
    }

    private void RefreshShardActionState()
    {
        if (!_hasAr)
        {
            RunButton.Disabled = true;
            RunButton.ToolTip = Loc.GetString("netrunning-cyberdeck-run-requires-ar");
            EditButton.Disabled = false;
            EjectButton.Disabled = false;
            return;
        }

        if (_selectedShard == null || !_shardData.TryGetValue(_selectedShard.Value, out var data))
        {
            RunButton.Disabled = false;
            RunButton.ToolTip = null;
            EditButton.Disabled = false;
            EjectButton.Disabled = false;
            return;
        }

        var runtimeState = data.RuntimeState;
        var busy = runtimeState != MetaProgramRuntimeState.Ready;
        EditButton.Disabled = busy;
        EjectButton.Disabled = busy;
        if (busy)
        {
            RunButton.Disabled = true;
            RunButton.ToolTip = Loc.GetString("netrunning-program-state-running");
            return;
        }

        if (data.Kind == MetaProgramKind.DaemonDefensive)
        {
            RunButton.Disabled = true;
            RunButton.ToolTip = Loc.GetString("netrunning-cyberdeck-run-defensive-install");
            return;
        }

        RunButton.Disabled = false;
        RunButton.ToolTip = null;
    }

    private string GetShardDisplayName((string Name, string Source, MetaProgramKind Kind, int RamCost, MetaProgramRuntimeState RuntimeState) data)
    {
        var prefix = data.Kind == MetaProgramKind.DaemonDefensive
            ? Loc.GetString("netrunning-cyberdeck-defensive-prefix") + " "
            : string.Empty;
        var stateText = data.RuntimeState switch
        {
            MetaProgramRuntimeState.Running => Loc.GetString("netrunning-program-state-running"),
            _ => Loc.GetString("netrunning-program-state-ready")
        };
        return $"{prefix}{data.Name} [RAM:{data.RamCost}] [{stateText}]";
    }
}
