using System.Linq;
using Content.Shared._NC.Netrunning.Components;
using Content.Shared._NC.Netrunning.Meta;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberdeckTerminalWindow : DefaultWindow
{
    public event Action<string, string, MetaProgramKind, NetEntity?>? OnCompileRequested;
    public event Action<NetEntity>? OnRunRequested;
    public event Action<NetEntity>? OnEjectRequested;
    public event Action? OnHotSimRequested;
    public event Action<string, NetEntity>? OnConstructRequested;

    private NetEntity? _selectedShard;
    private Dictionary<NetEntity, (string Name, string Source, MetaProgramKind Kind)> _shardData = new();
    private List<NetModuleInfo> _availableModules = new();
    private List<NetAnchorInfo> _availableAnchors = new();
    private string _logBuffer = "";
    private bool _hasAr;

    public CyberdeckTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        HotSimButton.OnPressed += _ => OnHotSimRequested?.Invoke();
        ConstructButton.OnPressed += _ =>
        {
            var selectedModule = ModuleList.GetSelected().FirstOrDefault();
            var selectedPort = PortList.GetSelected().FirstOrDefault();

            if (selectedModule != null && selectedPort != null)
            {
                OnConstructRequested?.Invoke((string)selectedModule.Metadata!, (NetEntity)selectedPort.Metadata!);
            }
        };

        ModuleList.OnItemSelected += args =>
        {
            var id = (string)args.ItemList[args.ItemIndex].Metadata!;
            var module = _availableModules.FirstOrDefault(m => m.Id == id);
            if (module != null)
            {
                ModuleDesc.SetMessage($"Name: {module.Name}\nServer Load: {module.RamCost}\nPrice: {module.Price} Eddies\n\n{module.Description}");
            }
        };

        CompileNewButton.OnPressed += _ => OnCompileRequested?.Invoke(
            Rope.Collapse(CodeInput.TextRope),
            NameInput.Text,
            DefensiveModeCheck.Pressed ? MetaProgramKind.DaemonDefensive : MetaProgramKind.Standard,
            null);
        SaveButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
            {
                OnCompileRequested?.Invoke(
                    Rope.Collapse(CodeInput.TextRope),
                    NameInput.Text,
                    DefensiveModeCheck.Pressed ? MetaProgramKind.DaemonDefensive : MetaProgramKind.Standard,
                    _selectedShard);
            }
        };

        RunButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnRunRequested?.Invoke(_selectedShard.Value);
        };

        EditButton.OnPressed += _ =>
        {
            if (_selectedShard != null && _shardData.TryGetValue(_selectedShard.Value, out var data))
            {
                CodeInput.TextRope = new Rope.Leaf(data.Source);
                NameInput.Text = data.Name;
                DefensiveModeCheck.Pressed = data.Kind == MetaProgramKind.DaemonDefensive;
            }
        };

        EjectButton.OnPressed += _ =>
        {
            if (_selectedShard != null)
                OnEjectRequested?.Invoke(_selectedShard.Value);
        };

        ShardList.OnItemSelected += args =>
        {
            _selectedShard = (NetEntity) ShardList[args.ItemIndex].Metadata!;
            RefreshShardActionState();
        };
    }

    public void UpdateState(CyberdeckUiState state)
    {
        _hasAr = state.HasAR;
        RamLabel.Text = $"RAM: {state.CurrentRam}/{state.MaxRam}";
        TraceLabel.Text = $"Trace: {state.CurrentTrace}";
        StorageLabel.Text = $"Storage: {state.StorageUsed}/{state.StorageCapacity}";
        ServerLoadLabel.Text = state.ActiveServer == null
            ? "Server: offline"
            : $"Server: {state.ServerUsedLoad}/{state.ServerMaxLoad} load";
        
        if (!state.HasAR)
        {
            TargetLabel.Text = "Connection: OFFLINE (AR Overlay Required)";
            TargetLabel.FontColorOverride = Color.Red;
        }
        else
        {
            TargetLabel.Text = state.ActiveTarget != null ? $"Link: Linked" : "Link: Ready";
            TargetLabel.FontColorOverride = state.ActiveTarget != null ? Color.Green : Color.LightGray;
        }

        _shardData.Clear();
        foreach (var (shard, name, source, kind) in state.Shards)
        {
            _shardData[shard] = (name, source, kind);
        }

        ShardList.Clear();
        foreach (var (shard, data) in _shardData)
        {
            var displayName = data.Kind == MetaProgramKind.DaemonDefensive ? $"[DEF] {data.Name}" : data.Name;
            ShardList.AddItem(displayName, metadata: shard);
        }

        ModuleList.Clear();
        _availableModules = state.AvailableModules;
        foreach (var module in _availableModules)
        {
            ModuleList.AddItem(module.Name, metadata: module.Id);
        }

        PortList.Clear();
        _availableAnchors = state.AvailableAnchors;
        foreach (var port in _availableAnchors)
        {
            var text = port.Connected ? $"[Occupied] Port {port.Dir}" : $"Port {port.Dir}";
            var item = PortList.AddItem(text, metadata: port.Uid);
            item.Disabled = port.Connected;
        }

        ConstructButton.Disabled = state.ActiveServer == null || !state.HasServerAdminAccess;
        ConstructButton.ToolTip = ConstructButton.Disabled
            ? "Requires direct server maintenance link or rooted network access."
            : null;

        if (_selectedShard == null)
            DefensiveModeCheck.Pressed = false;

        RefreshShardActionState();
    }

    public void AddLog(string text)
    {
        _logBuffer += text + "\n";
        LogOutput.SetMessage(_logBuffer);
    }

    private void RefreshShardActionState()
    {
        if (!_hasAr)
        {
            RunButton.Disabled = true;
            RunButton.ToolTip = "Requires AR Glasses to execute remote scripts.";
            return;
        }

        if (_selectedShard == null || !_shardData.TryGetValue(_selectedShard.Value, out var data))
        {
            RunButton.Disabled = false;
            RunButton.ToolTip = null;
            return;
        }

        if (data.Kind == MetaProgramKind.DaemonDefensive)
        {
            RunButton.Disabled = true;
            RunButton.ToolTip = "Defensive daemon shards must be installed in a protected node.";
            return;
        }

        RunButton.Disabled = false;
        RunButton.ToolTip = null;
    }
}
