using Content.Shared._NC.Netrunning.Components;
using Content.Shared._NC.Netrunning.Meta;
using Robust.Shared.GameObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.IoC;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Content.Client.Viewport;
using Robust.Shared.Maths;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetNodeWindow : DefaultWindow
{
    private static readonly Vector2 DeviceViewportZoom = new(0.7f, 0.7f);

    public event Action<string>? OnControlAction;
    public event Action<NetEntity>? OnExecuteShard;

    private readonly ScalingViewport _viewport;
    private readonly FixedEye _syntheticEye = new();
    private readonly List<NetNodeShardInfo> _shards = new();
    private bool _hasLinkedDeck;
    private EntityUid? _physicalUid;
    private NetDeviceNodeKind _deviceKind;

    public NetNodeWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("netrunning-node-title");
        DeviceNameLabel.Text = Loc.GetString("netrunning-node-unknown-title");
        DeviceKindLabel.Text = Loc.GetString("netrunning-node-unknown-kind");
        ViewportTitleLabel.Text = Loc.GetString("netrunning-node-viewport-title");
        ViewportHintLabel.Text = Loc.GetString("netrunning-node-viewport-default");
        ScriptsTitleLabel.Text = Loc.GetString("netrunning-node-scripts-title");
        ShardStatusLabel.Text = Loc.GetString("netrunning-node-scripts-default");
        ExecuteShardButton.Text = Loc.GetString("netrunning-node-execute");
        ControlTitleLabel.Text = Loc.GetString("netrunning-node-control-title");
        ToggleButton.Text = Loc.GetString("netrunning-node-toggle");
        ScanButton.Text = Loc.GetString("netrunning-node-rescan");

        _viewport = new ScalingViewport
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            MinHeight = 200,
            ViewportSize = new Vector2i(384, 256)
        };
        ViewportContainer.AddChild(_viewport);

        // Synthetic device viewport acts like a remote live feed rather than local FOV.
        _syntheticEye.DrawFov = false;
        _syntheticEye.DrawLight = true;
        _syntheticEye.Zoom = DeviceViewportZoom;

        ToggleButton.OnPressed += _ => OnControlAction?.Invoke("toggle");
        ScanButton.OnPressed += _ => OnControlAction?.Invoke("scan");
        ExecuteShardButton.OnPressed += _ =>
        {
            var selected = ShardList.GetSelected().FirstOrDefault();
            if (selected?.Metadata is NetEntity shard)
                OnExecuteShard?.Invoke(shard);
        };
        ShardList.OnItemSelected += _ => RefreshButtons();
    }

    public void UpdateState(NetNodeUiState state)
    {
        DeviceNameLabel.Text = Loc.GetString("netrunning-node-title-name", ("name", state.DeviceName.ToUpperInvariant()));
        DeviceKindLabel.Text = state.Kind == NetDeviceNodeKind.CameraGroup
            ? Loc.GetString("netrunning-node-kind-camera-group", ("kind", GetKindLabel(state.Kind)), ("count", state.DeviceCount))
            : Loc.GetString("netrunning-node-kind", ("kind", GetKindLabel(state.Kind)));
        ViewportHintLabel.Text = state.Kind == NetDeviceNodeKind.CameraGroup
            ? Loc.GetString("netrunning-node-viewport-camera")
            : Loc.GetString("netrunning-node-viewport-device");

        ShardList.Clear();
        _shards.Clear();
        _shards.AddRange(state.AvailableShards);

        foreach (var shard in _shards.OrderBy(s => s.Name))
        {
            var kind = shard.Kind == Content.Shared._NC.Netrunning.Meta.MetaProgramKind.DaemonDefensive
                ? Loc.GetString("netrunning-node-shard-kind-daemon")
                : Loc.GetString("netrunning-node-shard-kind-script");
            ShardList.AddItem(GetShardDisplayName(shard, kind), metadata: shard.Uid);
        }

        ShardStatusLabel.Text = state.HasLinkedDeck
            ? _shards.Count > 0
                ? Loc.GetString("netrunning-node-shard-ready")
                : Loc.GetString("netrunning-node-shard-empty")
            : Loc.GetString("netrunning-node-shard-no-deck");

        _hasLinkedDeck = state.HasLinkedDeck;
        _physicalUid = IoCManager.Resolve<IEntityManager>().GetEntity(state.PhysicalDevice);
        _deviceKind = state.Kind;

        UpdateViewportSource();
        RefreshButtons();
    }

    private void RefreshButtons()
    {
        var selected = ShardList.GetSelected().FirstOrDefault();
        var selectedShard = selected?.Metadata is NetEntity uid
            ? _shards.FirstOrDefault(shard => shard.Uid == uid)
            : null;
        ExecuteShardButton.Disabled = !_hasLinkedDeck || selectedShard == null ||
                                      selectedShard.RuntimeState != MetaProgramRuntimeState.Ready;
    }

    private static string GetKindLabel(NetDeviceNodeKind kind)
    {
        return kind switch
        {
            NetDeviceNodeKind.Door => Loc.GetString("netrunning-node-kind-door"),
            NetDeviceNodeKind.CameraGroup => Loc.GetString("netrunning-node-kind-camera"),
            NetDeviceNodeKind.DataGate => Loc.GetString("netrunning-node-kind-gate"),
            _ => Loc.GetString("netrunning-node-kind-device"),
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_viewport.Eye == _syntheticEye)
            UpdateSyntheticEyePosition();

        foreach (var item in ShardList)
        {
            if (item.Metadata is not NetEntity uid)
                continue;

            var shard = _shards.FirstOrDefault(entry => entry.Uid == uid);
            if (shard == null)
                continue;

            var kind = shard.Kind == MetaProgramKind.DaemonDefensive
                ? Loc.GetString("netrunning-node-shard-kind-daemon")
                : Loc.GetString("netrunning-node-shard-kind-script");
            item.Text = GetShardDisplayName(shard, kind);
        }

        RefreshButtons();
    }

    private string GetShardDisplayName(NetNodeShardInfo shard, string kind)
    {
        var stateText = shard.RuntimeState switch
        {
            MetaProgramRuntimeState.Running => Loc.GetString("netrunning-program-state-running"),
            _ => Loc.GetString("netrunning-program-state-ready")
        };
        return $"{shard.Name} [{kind}] RAM:{shard.RamCost} [{stateText}]";
    }

    private void UpdateViewportSource()
    {
        if (_physicalUid is not { } physicalUid)
        {
            _viewport.Eye = null;
            return;
        }

        var entMan = IoCManager.Resolve<IEntityManager>();
        if (_deviceKind == NetDeviceNodeKind.CameraGroup &&
            entMan.TryGetComponent<EyeComponent>(physicalUid, out var eye) &&
            eye.Eye != null)
        {
            _viewport.Eye = eye.Eye;
            return;
        }

        _syntheticEye.Zoom = DeviceViewportZoom;
        UpdateSyntheticEyePosition();
        _viewport.Eye = _syntheticEye;
    }

    private void UpdateSyntheticEyePosition()
    {
        if (_physicalUid is not { } physicalUid)
            return;

        var entMan = IoCManager.Resolve<IEntityManager>();
        var xforms = entMan.System<SharedTransformSystem>();
        var mapCoords = xforms.GetMapCoordinates(physicalUid);

        if (mapCoords.MapId == MapId.Nullspace)
            return;

        _syntheticEye.Position = mapCoords;
        _syntheticEye.Rotation = Angle.Zero;
    }
}
