using Content.Shared._NC.Netrunning.Components;
using Robust.Shared.GameObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.IoC;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Content.Client.Viewport;
using Robust.Shared.Maths;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetNodeWindow : DefaultWindow
{
    private static readonly Vector2 DeviceViewportZoom = new(0.7f, 0.7f);

    public event Action<string>? OnControlAction;
    public event Action<NetEntity>? OnExecuteShard;

    private readonly ScalingViewport _viewport;
    private readonly FixedEye _syntheticEye = new();
    private readonly List<NetNodeShardInfo> _shards = new();
    private bool _hasLinkedDeck;
    private EntityUid? _physicalUid;
    private NetDeviceNodeKind _deviceKind;

    public NetNodeWindow()
    {
        RobustXamlLoader.Load(this);

        _viewport = new ScalingViewport
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            MinHeight = 200,
            ViewportSize = new Vector2i(384, 256)
        };
        ViewportContainer.AddChild(_viewport);

        // Synthetic device viewport acts like a remote live feed rather than local FOV.
        _syntheticEye.DrawFov = false;
        _syntheticEye.DrawLight = true;
        _syntheticEye.Zoom = DeviceViewportZoom;

        ToggleButton.OnPressed += _ => OnControlAction?.Invoke("toggle");
        ScanButton.OnPressed += _ => OnControlAction?.Invoke("scan");
        ExecuteShardButton.OnPressed += _ =>
        {
            var selected = ShardList.GetSelected().FirstOrDefault();
            if (selected?.Metadata is NetEntity shard)
                OnExecuteShard?.Invoke(shard);
        };
        ShardList.OnItemSelected += _ => RefreshButtons();
    }

    public void UpdateState(NetNodeUiState state)
    {
        DeviceNameLabel.Text = $"УЗЕЛ://{state.DeviceName.ToUpperInvariant()}";
        DeviceKindLabel.Text = state.Kind == NetDeviceNodeKind.CameraGroup
            ? $"ТИП: {GetKindLabel(state.Kind)} / КАМЕР В ГРУППЕ: {state.DeviceCount}"
            : $"ТИП: {GetKindLabel(state.Kind)}";
        ViewportHintLabel.Text = state.Kind == NetDeviceNodeKind.CameraGroup
            ? "Живой видеопоток камеры. Отображается активный физический узел."
            : "Живой обзор физического устройства. Центрирован на узле, радиус наблюдения около 4 тайлов.";

        ShardList.Clear();
        _shards.Clear();
        _shards.AddRange(state.AvailableShards);

        foreach (var shard in _shards.OrderBy(s => s.Name))
        {
            var kind = shard.Kind == Content.Shared._NC.Netrunning.Meta.MetaProgramKind.DaemonDefensive ? "ДЕМОН" : "СКРИПТ";
            ShardList.AddItem($"{shard.Name} [{kind}] RAM:{shard.RamCost}", metadata: shard.Uid);
        }

        ShardStatusLabel.Text = state.HasLinkedDeck
            ? _shards.Count > 0
                ? "Выбери скрипт из деки и выпусти его в текущий узел."
                : "В деке нет доступных META-скриптов для запуска."
            : "Дека не привязана к аватару. Скрипты недоступны.";

        _hasLinkedDeck = state.HasLinkedDeck;
        _physicalUid = IoCManager.Resolve<IEntityManager>().GetEntity(state.PhysicalDevice);
        _deviceKind = state.Kind;

        UpdateViewportSource();
        RefreshButtons();
    }

    private void RefreshButtons()
    {
        ExecuteShardButton.Disabled = !_hasLinkedDeck || _shards.Count == 0 || !ShardList.GetSelected().Any();
    }

    private static string GetKindLabel(NetDeviceNodeKind kind)
    {
        return kind switch
        {
            NetDeviceNodeKind.Door => "ШЛЮЗ",
            NetDeviceNodeKind.CameraGroup => "КАМЕРНЫЙ УЗЕЛ",
            NetDeviceNodeKind.DataGate => "ШЛЮЗ СЕТИ",
            _ => "УСТРОЙСТВО",
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_viewport.Eye == _syntheticEye)
            UpdateSyntheticEyePosition();
    }

    private void UpdateViewportSource()
    {
        if (_physicalUid is not { } physicalUid)
        {
            _viewport.Eye = null;
            return;
        }

        var entMan = IoCManager.Resolve<IEntityManager>();
        if (_deviceKind == NetDeviceNodeKind.CameraGroup &&
            entMan.TryGetComponent<EyeComponent>(physicalUid, out var eye) &&
            eye.Eye != null)
        {
            _viewport.Eye = eye.Eye;
            return;
        }

        _syntheticEye.Zoom = DeviceViewportZoom;
        UpdateSyntheticEyePosition();
        _viewport.Eye = _syntheticEye;
    }

    private void UpdateSyntheticEyePosition()
    {
        if (_physicalUid is not { } physicalUid)
            return;

        var entMan = IoCManager.Resolve<IEntityManager>();
        var xforms = entMan.System<SharedTransformSystem>();
        var mapCoords = xforms.GetMapCoordinates(physicalUid);

        if (mapCoords.MapId == MapId.Nullspace)
            return;

        _syntheticEye.Position = mapCoords;
        _syntheticEye.Rotation = Angle.Zero;
    }
}
