using Content.Shared._NC.Netrunning.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Shared.IoC;
using Robust.Client.GameObjects;
using Content.Client.Viewport;
using Robust.Shared.Maths;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetNodeWindow : DefaultWindow
{
    public event Action<string>? OnControlAction;
    private ScalingViewport _viewport;

    public NetNodeWindow()
    {
        RobustXamlLoader.Load(this);

        _viewport = new ScalingViewport
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            MinHeight = 200,
            ViewportSize = new Vector2i(320, 240)
        };
        ViewportContainer.AddChild(_viewport);

        ToggleButton.OnPressed += _ => OnControlAction?.Invoke("toggle");
        ScanButton.OnPressed += _ => OnControlAction?.Invoke("scan");
    }

    public void UpdateState(NetNodeUiState state)
    {
        DeviceNameLabel.Text = $"Target: {state.DeviceName}";
        
        var entMan = IoCManager.Resolve<IEntityManager>();
        var physicalUid = entMan.GetEntity(state.PhysicalDevice);
        
        if (entMan.TryGetComponent<EyeComponent>(physicalUid, out var eye))
        {
            _viewport.Eye = eye.Eye;
        }
    }
}
