using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._NC.Netrunning.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetServerConsoleWindow : DefaultWindow
{
    public event Action? OnRefreshRequested;
    public event Action<string, NetEntity>? OnConstructRequested;

    private List<NetModuleInfo> _availableModules = new();
    private List<NetAnchorInfo> _availableAnchors = new();

    public NetServerConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        ConstructButton.OnPressed += _ =>
        {
            var selectedModule = ModuleList.GetSelected().FirstOrDefault();
            var selectedPort = PortList.GetSelected().FirstOrDefault();
            if (selectedModule != null && selectedPort != null)
                OnConstructRequested?.Invoke((string) selectedModule.Metadata!, (NetEntity) selectedPort.Metadata!);
        };

        ModuleList.OnItemSelected += args =>
        {
            var id = (string) args.ItemList[args.ItemIndex].Metadata!;
            var module = _availableModules.FirstOrDefault(m => m.Id == id);
            if (module != null)
                ModuleDesc.SetMessage($"[color=#7fd3ff]{module.Name}[/color]\nLoad: {module.RamCost}\nPrice: {module.Price}\n\n{module.Description}");

            RefreshConstructState();
        };

        PortList.OnItemSelected += _ => RefreshConstructState();
    }

    public void UpdateState(NetServerUiState state)
    {
        ServerNameLabel.Text = state.ServerName;
        ProviderLabel.Text = state.ProviderLabel;
        LoadLabel.Text = $"Load: {state.UsedLoad}/{state.MaxLoad}";
        ModuleLabel.Text = $"Modules: {state.ModuleCount}/{state.ModuleLimit}";
        DeviceCountLabel.Text = $"Devices: {state.ConnectedDeviceCount}";
        DaemonLabel.Text = state.HasDaemonShard ? "Daemon: installed" : "Daemon: empty";

        DeviceList.Clear();
        foreach (var device in state.ConnectedDevices.OrderBy(d => d.Class).ThenBy(d => d.Name))
        {
            DeviceList.AddItem($"[{device.Class}] {device.Name}", metadata: device.Uid);
        }

        PortList.Clear();
        _availableAnchors = state.AvailableAnchors;
        foreach (var port in _availableAnchors)
        {
            var text = port.Connected ? $"[Occupied] Port {port.Dir}" : $"Port {port.Dir}";
            var item = PortList.AddItem(text, metadata: port.Uid);
            item.Disabled = port.Connected;
        }

        ModuleList.Clear();
        _availableModules = state.AvailableModules;
        foreach (var module in _availableModules)
        {
            ModuleList.AddItem(module.Name, metadata: module.Id);
        }

        RefreshConstructState();
    }

    private void RefreshConstructState()
    {
        ConstructButton.Disabled = !ModuleList.GetSelected().Any() || !PortList.GetSelected().Any();
    }
}
