using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._NC.Netrunning.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetServerConsoleWindow : DefaultWindow
{
    public event Action? OnRefreshRequested;
    public event Action<string, NetEntity>? OnConstructRequested;
    public event Action? OnAdminRequested;

    private List<NetModuleInfo> _availableModules = new();
    private List<NetAnchorInfo> _availableAnchors = new();
    private float _constructGlow;
    private float _headerPulse;
    private float _loadRatio;
    private float _moduleRatio;
    private float _deviceRatio;
    private bool _hasDaemon;

    public NetServerConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        AdminButton.OnPressed += _ => OnAdminRequested?.Invoke();
        ConstructButton.OnPressed += _ =>
        {
            var selectedModule = ModuleList.GetSelected().FirstOrDefault();
            var selectedPort = PortList.GetSelected().FirstOrDefault();
            if (selectedModule != null && selectedPort != null)
                OnConstructRequested?.Invoke((string) selectedModule.Metadata!, (NetEntity) selectedPort.Metadata!);
        };

        ModuleList.OnItemSelected += args =>
        {
            var id = (string) args.ItemList[args.ItemIndex].Metadata!;
            var module = _availableModules.FirstOrDefault(m => m.Id == id);
            if (module != null)
                ModuleDesc.SetMessage($"[color=#7fd3ff]{module.Name}[/color]\nLoad: {module.RamCost}\nPrice: {module.Price}\n\n{module.Description}");

            RefreshConstructState();
        };

        PortList.OnItemSelected += _ => RefreshConstructState();
    }

    public void UpdateState(NetServerUiState state)
    {
        ServerNameLabel.Text = state.ServerName;
        ProviderLabel.Text = state.ProviderLabel;
        LoadLabel.Text = $"Нагрузка: {state.UsedLoad}/{state.MaxLoad}";
        ModuleLabel.Text = $"Модули: {state.ModuleCount}/{state.ModuleLimit}";
        DeviceCountLabel.Text = $"Узлы: {state.ConnectedDeviceCount}";
        DaemonLabel.Text = state.HasDaemonShard ? "Демон: установлен" : "Демон: пусто";
        AccessLabel.Text = state.AccessStatus;
        FooterLabel.Text = state.CanRequestAdmin
            ? "Подключенная дека обнаружена. Можно открыть локальный админ-сеанс."
            : "Для админ-сеанса сначала подключи деку к этому серверу.";
        AdminButton.Disabled = !state.CanRequestAdmin || state.HasAdminAccess;
        AdminButton.Text = state.HasPersistentRoot
            ? "Рут уже получен"
            : state.HasAdminAccess
                ? "Локальный доступ активен"
                : "Получить права администратора";

        _loadRatio = state.MaxLoad > 0 ? (float) state.UsedLoad / state.MaxLoad : 0f;
        _moduleRatio = state.ModuleLimit > 0 ? (float) state.ModuleCount / state.ModuleLimit : 0f;
        _deviceRatio = Math.Clamp(state.ConnectedDeviceCount / 16f, 0f, 1f);
        _hasDaemon = state.HasDaemonShard;
        TelemetryPanel.SetTelemetry(_loadRatio, _moduleRatio, _deviceRatio, _hasDaemon);

        DeviceList.Clear();
        foreach (var device in state.ConnectedDevices.OrderBy(d => d.Class).ThenBy(d => d.Name))
        {
            DeviceList.AddItem($"[{device.Class}] {device.Name}", metadata: device.Uid);
        }

        PortList.Clear();
        _availableAnchors = state.AvailableAnchors;
        foreach (var port in _availableAnchors)
        {
            var text = port.Connected ? $"[Occupied] Port {port.Dir}" : $"Port {port.Dir}";
            var item = PortList.AddItem(text, metadata: port.Uid);
            item.Disabled = port.Connected;
        }

        ModuleList.Clear();
        _availableModules = state.AvailableModules;
        foreach (var module in _availableModules)
        {
            ModuleList.AddItem(module.Name, metadata: module.Id);
        }

        RefreshConstructState();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _headerPulse += args.DeltaSeconds * (_hasDaemon ? 2.6f : 1.4f);
        var pulse = 0.86f + 0.14f * MathF.Sin(_headerPulse);
        ServerNameLabel.Modulate = Color.White.WithAlpha(pulse);
        DaemonBadge.Modulate = _hasDaemon
            ? Color.FromHex("#ff5e78").WithAlpha(0.68f + 0.26f * MathF.Sin(_headerPulse))
            : Color.White.WithAlpha(0.72f);

        var constructReady = !ConstructButton.Disabled;
        var glowTarget = constructReady ? 1f : 0f;
        _constructGlow = MathHelper.Lerp(_constructGlow, glowTarget, 5f * args.DeltaSeconds);
        ConstructButton.Modulate = Color.InterpolateBetween(Color.White, Color.FromHex("#ffc86a"), _constructGlow * 0.6f);

        LoadLabel.Modulate = _loadRatio > 0.85f
            ? Color.FromHex("#ff8870")
            : Color.FromHex("#8ed9ff");
        ModuleLabel.Modulate = _moduleRatio > 0.85f
            ? Color.FromHex("#ffcc70")
            : Color.FromHex("#8ed9ff");
        DeviceCountLabel.Modulate = Color.FromHex("#95ffaf");
        AccessLabel.Modulate = AdminButton.Disabled
            ? Color.FromHex("#9aa8ad")
            : Color.FromHex("#ffcf73");
    }

    private void RefreshConstructState()
    {
        ConstructButton.Disabled = !ModuleList.GetSelected().Any() || !PortList.GetSelected().Any();
        if (ConstructButton.Disabled)
            ModuleDesc.SetMessage("[color=#768692]Выбери пакет комнаты и свободный порт, чтобы начать сборку.[/color]");
    }
}
