using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._NC.Netrunning.Components;
using Content.Shared._NC.Netrunning.Meta;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Maths;
using Robust.Shared.IoC;
using Robust.Shared.Timing;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetServerConsoleWindow : DefaultWindow
{
    public event Action? OnRefreshRequested;
    public event Action<string, NetEntity>? OnConstructRequested;
    public event Action? OnAdminRequested;
    public event Action<NetEntity, Vector2i>? OnTopologyMoveRequested;

    private List<NetModuleInfo> _availableModules = new();
    private List<NetAnchorInfo> _availableAnchors = new();
    private List<NetTopologyMapEntry> _topologyEntries = new();
    private NetEntity? _selectedTopologyEntity;
    private Vector2i _topologyMinTile = new(-4, -4);
    private Vector2i _topologyMaxTile = new(4, 4);
    private float _constructGlow;
    private float _headerPulse;
    private float _loadRatio;
    private float _moduleRatio;
    private float _deviceRatio;
    private bool _hasDaemon;
    private int _daemonShardCount;
    private int _daemonSlotCount;
    private MetaProgramRuntimeState _daemonRuntimeState;
    private bool _hasTopologyAdminAccess;

    public NetServerConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("netrunning-server-console-title");
        Tabs.SetTabTitle(0, Loc.GetString("netrunning-ui-tab-overview"));
        Tabs.SetTabTitle(1, Loc.GetString("netrunning-ui-tab-topology"));
        ServerNameLabel.Text = Loc.GetString("netrunning-server-console-unknown");
        HeaderSubtitleLabel.Text = Loc.GetString("netrunning-server-console-subtitle");
        ProviderLabel.Text = Loc.GetString("netrunning-server-provider-none");
        LoadLabel.Text = Loc.GetString("netrunning-ui-label-load", ("used", 0), ("max", 0));
        RuntimeLabel.Text = Loc.GetString("netrunning-ui-label-runtime", ("active", 0), ("max", 0));
        ModuleLabel.Text = Loc.GetString("netrunning-ui-label-modules", ("count", 0), ("limit", 0));
        DeviceCountLabel.Text = Loc.GetString("netrunning-ui-label-nodes", ("count", 0));
        DaemonLabel.Text = Loc.GetString("netrunning-ui-daemon-empty-count", ("count", 0), ("slots", 0));
        DevicesTitleLabel.Text = Loc.GetString("netrunning-server-devices-title");
        DevicesHintLabel.Text = Loc.GetString("netrunning-server-devices-hint");
        RefreshButton.Text = Loc.GetString("netrunning-server-refresh");
        PortsTitleLabel.Text = Loc.GetString("netrunning-server-ports-title");
        PortsHintLabel.Text = Loc.GetString("netrunning-server-ports-hint");
        ModuleTitleLabel.Text = Loc.GetString("netrunning-server-module-title");
        ModuleHintLabel.Text = Loc.GetString("netrunning-server-module-hint");
        ConstructButton.Text = Loc.GetString("netrunning-server-construct");
        PlacementTitleLabel.Text = Loc.GetString("netrunning-server-placement-title");
        TopologyStatusLabel.Text = Loc.GetString("netrunning-ui-topology-ready");
        MapTitleLabel.Text = Loc.GetString("netrunning-server-map-title");
        MapHintLabel.Text = Loc.GetString("netrunning-server-map-hint");
        AccessLabel.Text = Loc.GetString("netrunning-server-access-none");
        FooterLabel.Text = Loc.GetString("netrunning-ui-footer-admin-missing-deck");
        AdminButton.Text = Loc.GetString("netrunning-ui-admin-request");

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        AdminButton.OnPressed += _ => OnAdminRequested?.Invoke();
        ConstructButton.OnPressed += _ =>
        {
            var selectedModule = ModuleList.GetSelected().FirstOrDefault();
            var selectedPort = PortList.GetSelected().FirstOrDefault();
            if (selectedModule != null && selectedPort != null)
                OnConstructRequested?.Invoke((string) selectedModule.Metadata!, (NetEntity) selectedPort.Metadata!);
        };

        ModuleList.OnItemSelected += args =>
        {
            var id = (string) args.ItemList[args.ItemIndex].Metadata!;
            var module = _availableModules.FirstOrDefault(m => m.Id == id);
            if (module != null)
                ModuleDesc.SetMessage(Loc.GetString("netrunning-ui-module-desc",
                    ("name", module.Name),
                    ("load", module.RamCost),
                    ("price", module.Price),
                    ("desc", module.Description)));

            RefreshConstructState();
        };

        PortList.OnItemSelected += _ => RefreshConstructState();
        TopologyList.OnItemSelected += args =>
        {
            _selectedTopologyEntity = (NetEntity) args.ItemList[args.ItemIndex].Metadata!;
            RefreshTopologySelection();
        };

        TopologyMap.OnTilePressed += tile =>
        {
            if (!_hasTopologyAdminAccess || _selectedTopologyEntity is not { } selected)
                return;

            OnTopologyMoveRequested?.Invoke(selected, tile);
        };
    }

    public void UpdateState(NetServerUiState state)
    {
        ServerNameLabel.Text = state.ServerName;
        ProviderLabel.Text = state.ProviderLabel;
        LoadLabel.Text = Loc.GetString("netrunning-ui-label-load", ("used", state.UsedLoad), ("max", state.MaxLoad));
        RuntimeLabel.Text = Loc.GetString("netrunning-ui-label-runtime",
            ("active", state.ActiveMetaPrograms), ("max", state.MaxConcurrentMetaPrograms));
        ModuleLabel.Text = Loc.GetString("netrunning-ui-label-modules", ("count", state.ModuleCount), ("limit", state.ModuleLimit));
        DeviceCountLabel.Text = Loc.GetString("netrunning-ui-label-nodes", ("count", state.ConnectedDeviceCount));
        _hasDaemon = state.HasDaemonShard;
        _daemonShardCount = state.DaemonShardCount;
        _daemonSlotCount = state.DaemonSlotCount;
        _daemonRuntimeState = state.DaemonRuntimeState;
        RefreshDaemonLabel();
        AccessLabel.Text = state.AccessStatus;
        FooterLabel.Text = state.CanRequestAdmin
            ? Loc.GetString("netrunning-ui-footer-admin-ready")
            : Loc.GetString("netrunning-ui-footer-admin-missing-deck");
        AdminButton.Disabled = !state.CanRequestAdmin || state.HasAdminAccess;
        AdminButton.Text = state.HasPersistentRoot
            ? Loc.GetString("netrunning-ui-admin-root-owned")
            : state.HasAdminAccess
                ? Loc.GetString("netrunning-ui-admin-local-active")
                : Loc.GetString("netrunning-ui-admin-request");

        _loadRatio = state.MaxLoad > 0 ? (float) state.UsedLoad / state.MaxLoad : 0f;
        _moduleRatio = state.ModuleLimit > 0 ? (float) state.ModuleCount / state.ModuleLimit : 0f;
        _deviceRatio = Math.Clamp(state.ConnectedDeviceCount / 16f, 0f, 1f);
        _hasTopologyAdminAccess = state.HasAdminAccess;
        TelemetryPanel.SetTelemetry(_loadRatio, _moduleRatio, _deviceRatio, _hasDaemon);

        DeviceList.Clear();
        foreach (var device in state.ConnectedDevices.OrderBy(d => d.Class).ThenBy(d => d.Name))
        {
            DeviceList.AddItem($"[{device.Class}] {device.Name}", metadata: device.Uid);
        }

        PortList.Clear();
        _availableAnchors = state.AvailableAnchors;
        foreach (var port in _availableAnchors)
        {
            var text = port.Connected
                ? Loc.GetString("netrunning-ui-port-occupied", ("dir", port.Dir))
                : Loc.GetString("netrunning-ui-port-free", ("dir", port.Dir));
            var item = PortList.AddItem(text, metadata: port.Uid);
            item.Disabled = port.Connected;
        }

        ModuleList.Clear();
        _availableModules = state.AvailableModules;
        foreach (var module in _availableModules)
        {
            ModuleList.AddItem(module.Name, metadata: module.Id);
        }

        _topologyEntries = state.TopologyEntries.OrderBy(e => e.Class).ThenBy(e => e.Name).ToList();
        _topologyMinTile = state.TopologyMinTile;
        _topologyMaxTile = state.TopologyMaxTile;
        RebuildTopologyList();

        RefreshConstructState();
        RefreshTopologyStatus();
        RefreshTopologySelection();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _headerPulse += args.DeltaSeconds * (_hasDaemon ? 2.6f : 1.4f);
        var pulse = 0.86f + 0.14f * MathF.Sin(_headerPulse);
        ServerNameLabel.Modulate = Color.White.WithAlpha(pulse);
        DaemonBadge.Modulate = _hasDaemon
            ? Color.FromHex("#ff5e78").WithAlpha(0.68f + 0.26f * MathF.Sin(_headerPulse))
            : Color.White.WithAlpha(0.72f);

        RefreshDaemonLabel();

        var constructReady = !ConstructButton.Disabled;
        var glowTarget = constructReady ? 1f : 0f;
        _constructGlow = MathHelper.Lerp(_constructGlow, glowTarget, 5f * args.DeltaSeconds);
        ConstructButton.Modulate = Color.InterpolateBetween(Color.White, Color.FromHex("#ffc86a"), _constructGlow * 0.6f);

        LoadLabel.Modulate = _loadRatio > 0.85f
            ? Color.FromHex("#ff8870")
            : Color.FromHex("#8ed9ff");
        ModuleLabel.Modulate = _moduleRatio > 0.85f
            ? Color.FromHex("#ffcc70")
            : Color.FromHex("#8ed9ff");
        DeviceCountLabel.Modulate = Color.FromHex("#95ffaf");
        AccessLabel.Modulate = AdminButton.Disabled
            ? Color.FromHex("#9aa8ad")
            : Color.FromHex("#ffcf73");
    }

    private void RefreshDaemonLabel()
    {
        if (!_hasDaemon)
        {
            DaemonLabel.Text = Loc.GetString("netrunning-ui-daemon-empty-count",
                ("count", _daemonShardCount),
                ("slots", _daemonSlotCount));
            return;
        }

        DaemonLabel.Text = _daemonRuntimeState switch
        {
            MetaProgramRuntimeState.Running => Loc.GetString("netrunning-ui-daemon-running-count",
                ("count", _daemonShardCount),
                ("slots", _daemonSlotCount)),
            _ => Loc.GetString("netrunning-ui-daemon-ready-count",
                ("count", _daemonShardCount),
                ("slots", _daemonSlotCount))
        };
    }

    private void RebuildTopologyList()
    {
        var previouslySelected = _selectedTopologyEntity;
        TopologyList.Clear();

        foreach (var entry in _topologyEntries)
        {
            var item = TopologyList.AddItem($"[{entry.Class}] {entry.Name}", metadata: entry.Uid);
            if (previouslySelected is { } selected && entry.Uid == selected)
                item.Selected = true;
        }

        if (_topologyEntries.Count == 0)
        {
            _selectedTopologyEntity = null;
            return;
        }

        if (previouslySelected is { } selectedEntry && _topologyEntries.Any(entry => entry.Uid == selectedEntry))
        {
            _selectedTopologyEntity = selectedEntry;
            return;
        }

        _selectedTopologyEntity = _topologyEntries[0].Uid;
        TopologyList[0].Selected = true;
    }

    private void RefreshConstructState()
    {
        ConstructButton.Disabled = !ModuleList.GetSelected().Any() || !PortList.GetSelected().Any();
        if (ConstructButton.Disabled)
            ModuleDesc.SetMessage(Loc.GetString("netrunning-ui-module-select-hint"));
    }

    private void RefreshTopologyStatus()
    {
        if (!_hasTopologyAdminAccess)
        {
            TopologyStatusLabel.Text = Loc.GetString("netrunning-ui-topology-locked");
            return;
        }

        if (_topologyEntries.Count == 0)
        {
            TopologyStatusLabel.Text = Loc.GetString("netrunning-ui-topology-empty");
            return;
        }

        TopologyStatusLabel.Text = Loc.GetString("netrunning-ui-topology-ready");
    }

    private void RefreshTopologySelection()
    {
        TopologyMap.SetTopology(_topologyMinTile, _topologyMaxTile, _topologyEntries, _selectedTopologyEntity);

        if (_selectedTopologyEntity is not { } selected)
        {
            TopologySelectionLabel.SetMessage(Loc.GetString("netrunning-ui-topology-none"));
            return;
        }

        var entry = _topologyEntries.FirstOrDefault(x => x.Uid == selected);
        if (entry == null)
        {
            TopologySelectionLabel.SetMessage(Loc.GetString("netrunning-ui-topology-none"));
            return;
        }

        var accessText = _hasTopologyAdminAccess
            ? Loc.GetString("netrunning-ui-topology-access-ready")
            : Loc.GetString("netrunning-ui-topology-access-locked");
        TopologySelectionLabel.SetMessage(Loc.GetString("netrunning-ui-topology-selected",
            ("name", entry.Name),
            ("class", entry.Class),
            ("x", entry.Tile.X),
            ("y", entry.Tile.Y),
            ("access", accessText)));
    }
}
