using System;
using System.Collections.Generic;
using Content.Shared._NC.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcStoreListingsView : PanelContainer
{
    private readonly List<string> _categories = new();
    private readonly List<string> _visibleIds = new();

    private NcListingGrid? _grid;
    private StoreMode _mode;
    private bool _syncingCategorySelect;

    private Func<string, string> _categoryDisplayName = static id => id;
    private Func<string, string> _categoryToolTip = static id => id;
    private string _searchLower = string.Empty;

    private IReadOnlyList<StoreListingData> _items = Array.Empty<StoreListingData>();
    private Func<string, int> _getBalanceForCurrency = static _ => 0;
    private Action<StoreListingData, int>? _onPressed;

    public string SelectedCategory { get; private set; } = string.Empty;

    public event Action<IReadOnlyList<string>>? VisibleIdsChanged;
    public event Action<string>? SelectedCategoryChanged;

    public NcStoreListingsView()
    {
        RobustXamlLoader.Load(this);
    }

    public void Initialize(
        StoreMode mode,
        IPrototypeManager proto,
        SpriteSystem sprites,
        string tabHeading,
        bool showMassSellButton)
    {
        _mode = mode;
        TabHeading.Text = tabHeading;

        MassSellRow.Visible = showMassSellButton;

        _grid = new NcListingGrid(mode, proto, sprites)
        {
            HorizontalExpand = true
        };

        _grid.VisibleIdsChanged += ids =>
        {
            _visibleIds.Clear();
            _visibleIds.AddRange(ids);
            VisibleIdsChanged?.Invoke(_visibleIds);
        };

        Pane.SetContent(_grid);
        // Important UX rule for the store: switching category must never inherit scroll
        // from a previous category. The pane owns this policy.
        Pane.RememberScrollPerKey = false;
        CategorySelect.PrefixMargin = false;

        CategorySelect.OnItemSelected += args =>
        {
            if (_syncingCategorySelect)
                return;

            if (args.Id < 0 || args.Id >= _categories.Count)
                return;

            CategorySelect.SelectId(args.Id);
            SelectedCategory = _categories[args.Id];
            CategorySelect.ToolTip = _categoryToolTip(SelectedCategory);
            Pane.SetKey(SelectedCategory);
            _grid.ResetPaging();
            Refresh();
            SelectedCategoryChanged?.Invoke(SelectedCategory);
        };
    }

    public void ConfigureCategories(Func<string, string> displayName, Func<string, string> toolTip)
    {
        _categoryDisplayName = displayName;
        _categoryToolTip = toolTip;
    }

    public void SetCategories(IReadOnlyList<string> categories)
    {
        _categories.Clear();
        foreach (var category in categories)
            _categories.Add(category);

        if (_categories.Count == 0)
        {
            SelectedCategory = string.Empty;
            CategorySelect.Clear();
            CategorySelect.AddItem(Loc.GetString("nc-store-select-category"), 0);
            CategorySelect.SelectId(0);
            CategorySelect.Disabled = true;
            Pane.SetKey(SelectedCategory);
            Refresh();
            return;
        }

        var selectedIndex = _categories.IndexOf(SelectedCategory);
        if (selectedIndex < 0)
        {
            selectedIndex = 0;
            SelectedCategory = _categories[0];
        }

        _syncingCategorySelect = true;
        CategorySelect.Clear();
        for (var i = 0; i < _categories.Count; i++)
        {
            var category = _categories[i];
            CategorySelect.AddItem(_categoryDisplayName(category), i);
        }

        CategorySelect.SelectId(selectedIndex);
        CategorySelect.Disabled = false;
        CategorySelect.ToolTip = _categoryToolTip(SelectedCategory);
        _syncingCategorySelect = false;

        Pane.SetKey(SelectedCategory);
        Refresh();
    }

    public void SetSearch(string searchLower)
    {
        _searchLower = searchLower ?? string.Empty;
        _grid?.ResetPaging();
        Refresh();
    }

    public void BindListingsData(
        IReadOnlyList<StoreListingData> items,
        Func<string, int> getBalanceForCurrency,
        Action<StoreListingData, int> onPressed)
    {
        _items = items;
        _getBalanceForCurrency = getBalanceForCurrency;
        _onPressed = onPressed;
        Refresh();
    }

    public void PrepareSearchIndex(List<string> productProtos) => _grid?.PrepareSearchIndex(productProtos);

    public void SyncAvailableIds(HashSet<string> availableIds) => _grid?.SyncAvailableIds(availableIds);

    public void UpdateDynamicOnly(Func<string, int> getBalanceForCurrency) => _grid?.UpdateDynamicOnly(getBalanceForCurrency);

    public void ClearCaches() => _grid?.ClearCaches();

    public Button MassSellButtonControl => MassSellButton;

    private void Refresh()
    {
        if (_grid == null)
            return;

        var hasSearch = !string.IsNullOrWhiteSpace(_searchLower);

        var count = _grid.Refresh(
            _items,
            SelectedCategory,
            _searchLower,
            _mode == StoreMode.Buy ? _getBalanceForCurrency : static _ => int.MaxValue,
            (d, qty) => _onPressed?.Invoke(d, qty));

        CategoryHeader.Visible = !string.IsNullOrEmpty(SelectedCategory) || hasSearch;

        if (!CategoryHeader.Visible)
        {
            CategoryHeader.Text = string.Empty;
            return;
        }

        if (!string.IsNullOrEmpty(SelectedCategory))
        {
            CategoryHeader.Text = _categoryDisplayName(SelectedCategory);
            return;
        }

        CategoryHeader.Text = _mode == StoreMode.Buy
            ? Loc.GetString("nc-store-search-results-buy", ("count", count))
            : Loc.GetString("nc-store-search-results-sell", ("count", count));
    }
}
